# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: resourcepack

      - name: compress pack
        uses: famima65536/resourcepack-compressor@v2
        with:
          source: resourcepack
          destination: artifact
          pack-name: SplaturnWeapons3D

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: resourcepack
          path: artifact/SplaturnWeapons3D.mcpack
